server:
  port: 8080

spring:
  application:
    name: gateway
    
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://localhost:8761/registry/eureka
      defaultZone: http://tcc-discovery.herokuapp.com/registry/eureka/
      
zuul:
  prefix: /api
  ignored-services: "*"
  host:
    max-total-connections: 10000
    max-per-route-connections: 50
  
  routes:
    integracao:
      path: /integracao/**
      service-id: integracao
      strip-prefix: false
      custom-sensitive-headers: true
      
    monitoramento:
      path: /monitoramento/**
      service-id: monitoramento
      strip-prefix: false
      custom-sensitive-headers: true
      